
// Arrays map out to LED marker number.

 char countryNames[][32] = { 
    "Sweden", 
    "Austria", 
    "Germany", 
    "Poland", 
    "Ireland", 
    "Italy", 
    "Britan", 
    "Spain", 
    "Iceland", 
    "Brazil", 
    "Argentina", 
    "Venezuela", 
    "Colombia", 
    "Mexico", 
    "United States", 
    "Canada",
    // Second PWM controller. 
    "Japan", 
    "South Korea", 
    "China", 
    "Mongolia", 
    "Australia", 
    "Indonesia", 
    "New Zealand", 
    "Thailand", 
    "Kazakhstan",     
    "India", 
    "Iran", 
    "Israel", 
    "Chad", 
    "South Africa", 
    "Russia", 
    "Ukraine"
    };


 char countryCodes[][32] = { 
    "SWE", 
    "AUT", 
    "DEU", 
    "POL", 
    "IRL", 
    "ITA", 
    "GBR", 
    "ESP", 
    "ISL", 
    "BRA", 
    "ARG", 
    "VEN", 
    "COL", 
    "MEX", 
    "USA", 
    "CAN",
    // Second PWM controller. 
    "JPN", 
    "PRK", 
    "CHN", 
    "MNG", 
    "AUS", 
    "IDN", 
    "NZL", 
    "THA", 
    "KAZ",     
    "IND", 
    "IRN", 
    "ISR", 
    "TCD", 
    "ZAF", 
    "RUS", 
    "UKR"
    }; 